### ISSUE TITLE
Reactive data ?

### ISSUE THREAD

**Issue by barisro** [jonjamz/forms#107]
I am a bit lost. It is possible I misunderstood the intention.

In the parent template I have a helper that returns the data document using a session variable which is set by click event of a table row.

    selectedRecord: function(){
        if(Session.get('SELECTED_ID')){
            return Clients.findOne(Session.get('SELECTED_ID'));
        }
        else{ return {}; }
    },

And the form template;
    {{#myForm data=selectedRecord schema=schema action=action}}
        {{> textInput field='Cod'}}
        {{> textInput field='Name'}}
        ...
        ...
    {{/myForm}}    

So I expect form data to be changed when session variable changes but it doesn't.
I also tried;
    {{#with selectedRecord}}
    {{#myForm data=this schema=schema action=action}}
        {{> textInput field='Cod'}}
        {{> textInput field='Name'}}
        ...
        ...
    {{/myForm}}
    {{/with}}

expecting it would be re-rendered without success. So what am I missing?

**Comment by jonjamz** [comment]
Check out this section of the docs:

https://github.com/meteortemplates/forms#working-with-reactive-form-data

Unless the entire form template gets re-rendered you have to specify how to
work with reactive data.

**Comment by barisro** [comment]
Thank you Jon. I thought that section was referring only to when data is changed by server. 
Just to be clear; I need to reset before refreshing if I want to display another object in the form right ?

**Comment by jonjamz** [comment]
Resetting should clear every form element completely so I would start with
this if working with an entirely new set of data.

Technically you are right, it's meant for dealing with remote changes to
the same document, but in your case it seems like the template is not being
destroyed and re-rendered when your session variable changes so I would try
this procedure and see if it works.

Jon

**Comment by barisro** [comment]
Thanks again. It looks kind of slow but it is working.

**Comment by jonjamz** [comment]
No problem. I have been meaning to revisit this project for a while but
simply haven't had the time. If you find anything that might improve
performance by all means let me know. :)

**Comment by barisro** [comment]
I think you should definitely revisit this project. The idea is great. And it looks very suitable to spawn other modular packages on top of it. 
I would like to contribute, just not so sure about my skill level. I will be using (slash testing) in the next days for a project heavily depends on forms. Please don't hesitate to contact me if there is anything I can do.
